name: base
channels:
  - defaults
dependencies:
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - pandas
  - partd
  - bokeh
  - dask
  - xlrd 
  - requests
  - networkx
  - PyGithub
  - jsonschema
  - scipy
